### ISSUE TITLE
public Abstract process manager links to CdpProcess which is not public

### ISSUE THREAD

**Issue by prakapenka** [webfolderio/cdp4j#66] opened 2017-12-12 13:36 UTC
We have public abstract 
https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/ProcessManager.java

When attempt to write own implementation in side project unable to to this since 
https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/CdpProcess.java

used in ProcessManager method signatrue - 
```
abstract void setProcess(CdpProcess process);
```
is not public and can't be referenced outside it's own package.

So let say I write my own 
```
SuperDuperProcessManager extends ProcessManager
```
To use it with Launcher for better process management

Unable to do this since my package is different from io/webfolder/cdp.

Please make CdpProcess public class.

Thank you in advance.

**Comment by webfolderio** [comment] 2017-12-17 16:13
It's fixed now.

**Closed** 2017-12-17 16:12 UTC

**Comment by pfurbacher** [comment] 2018-05-25 01:55
I beg to differ: the problem is not *really* fixed. Although the original author cited the package scope of ```CdpProcess``` as **a** problem, that is not **all** that is restricting you from implementing your own ```ProcessManager``` (which quite evidently he/she was trying to do). The package scoping of ```setProcess(CdpProcess process)``` ultimately prevents you from doing so, unless you create an ```io.webfolder.cdp``` package in your project (not cool/kosher/copacetic/ducky by any means).

Quoting  [ProcessManager.java](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/ProcessManager.java) in "master":

```
public abstract class ProcessManager {

    abstract void setProcess(CdpProcess process);

    public abstract boolean kill();
}
```
So this problem of being able to **cleanly/properly** implement your own ```ProcessManager``` (*e.g.*, one for Mac OS X -- which I did earlier today by creating the package ```io.webfolder.cdp``` in my project -- ouch, I really didn't want to do that but had to!) is not *really* fixed. The way to **completely** fix the problem which the original poster was dealing with is to change the scope of ```setProcess(...)``` to ```public``` as well.
