### ISSUE TITLE
NetworkRequestIntercepted Event, RequestIntercepted.interceptionId is null

### ISSUE THREAD

**Issue by paine1690** [webfolderio/cdp4j#10] opened 2017-07-04 02:03 UTC
my code:
`  public static void main(String[] args) throws IOException {
    Launcher launcher = new Launcher();

    try (SessionFactory factory = launcher.launch();
                        Session session = factory.create()) {
        session.navigate("https://www.sina.com");        
        Network network = session.getCommand().getNetwork();      
        network.enable();
        network.enableRequestInterception(true);  
       
        session.addEventListener((e, d) -> {
          if (NetworkRequestIntercepted.equals(e)) {
            System.out.println("adsd");
            RequestIntercepted ri = (RequestIntercepted) d;
            String id = ri.getInterceptionId();
            System.out.println(id + " " + ri.getRequest().getUrl() + " " + ri.getRedirectStatusCode());

            network.continueInterceptedRequest(id);
          }   
        });
        session.waitDocumentReady();
        
        Path file = createTempFile("screenshot", ".png");
        session.activate();
        byte[] data = session.captureScreenshot();
        write(file, data);
        if (isDesktopSupported()) {
          getDesktop().open(file.toFile());
      }
        
    } finally{
      System.out.println("end");
    }
  }`

but the in the console, id ia always null.

**Comment by paine1690** [comment] 2017-07-04 03:44
in the RequestIntercepted, except the Request, other member variables are all null.

**Comment by paine1690** [comment] 2017-07-05 08:29
It takes me a whole day to find that it is a bug caused by case sensitivity.
Smile with tired.jpg

**Comment by webfolderio** [comment] 2017-07-06 09:08
Thanks for the bug report. I merged your [pull request](https://github.com/webfolderio/cdp4j/pull/11). Let me know if the problem is still exist.

**Comment by paine1690** [comment] 2017-07-06 09:11
@webfolderio   thanks for reply. it is ok after the bug fixed.

**Closed** 2017-07-06 09:13 UTC
Labels: bug
